version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(依赖)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(工作流)"
