<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
    <ProjectReference Include="../PCL.Aurora.Domain/PCL.Aurora.Domain.csproj" />
    <ProjectReference Include="../PCL.Aurora.Platform.Abstractions/PCL.Aurora.Platform.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/PclCeMcModTranslations.buf" />
  </ItemGroup>
</Project>
