<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PclAuroraMicrosoftClientId Condition="'$(PclAuroraMicrosoftClientId)' == ''">$(PCL_AURORA_MS_CLIENT_ID)</PclAuroraMicrosoftClientId>
  </PropertyGroup>

  <ItemGroup Condition="'$(PclAuroraMicrosoftClientId)' != ''">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>PclAuroraMicrosoftClientId</_Parameter1>
      <_Parameter2>$(PclAuroraMicrosoftClientId)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PCL.Aurora.Application/PCL.Aurora.Application.csproj" />
    <ProjectReference Include="../PCL.Aurora.Infrastructure/PCL.Aurora.Infrastructure.csproj" />
    <ProjectReference Include="../PCL.Aurora.Platform.MacOS/PCL.Aurora.Platform.MacOS.csproj" />
  </ItemGroup>
</Project>
